M48
; DRILL file {KiCad 7.0.2-1.fc38} date mer 7 giu 2023, 17:49:06
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-07T17:49:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-1.fc38
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X5.0433Y-2.9313
X5.1614Y-2.9313
X6.2677Y-2.9331
X6.3858Y-2.9331
T0
M30
