M48
; DRILL file {KiCad 7.0.2-1.fc38} date ven 9 giu 2023, 15:19:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-09T15:19:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-1.fc38
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X3.25Y-1.6681
X3.3681Y-1.6681
X3.6004Y-1.6681
X3.7185Y-1.6681
T0
M30
