M48
; DRILL file {KiCad 7.0.2-1.fc38} date mar 6 giu 2023, 17:02:25
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-06T17:02:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-1.fc38
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X5.0433Y-2.9313
X5.1614Y-2.9313
X6.2677Y-2.9343
X6.3858Y-2.9343
T0
M30
